### ISSUE TITLE
Spaces are not being added in mobile number.

### ISSUE THREAD

**Issue by ganeshkalyank** [ganeshkalyank/contacts#1]
If we add a space in mobile number field, it is getting automatically removed. 
For example, if we use **+91 98765 43210**, it is being saved as **+919876543210**.

Anyone willing to fix this issue can comment. I'll assign. Multiple assignments are allowed and best PR will be merged.

**Comment by RashiSingh20** [comment]
@ganeshkalyank Hey I would like to work on this. Could you please assign it to me?

**Comment by noraa-junker** [comment]
I would like to work on that

**Comment by ganeshkalyank** [comment]
I want the space not to be removed. Actually, the space is being removed automatically somehow even without using the `str_replace` function.

**Comment by noraa-junker** [comment]
What browser do you use? Because I can't replicate this

**Comment by ganeshkalyank** [comment]
I use Chrome and even tested in Edge and Firefox. MariaDB 10 and PHP 8.

**Comment by noraa-junker** [comment]
It's because you set a maximum of 13 chars for the phone number. I increased it to 20 in the PR

**Comment by ganeshkalyank** [comment]
OK Great! I haven't tested it but it will fix that.
